trigger:
- main

stages:
- stage: Deploy
  displayName: Deploy to VM
  jobs:
  - deployment: VMDeploy
    displayName: Deploy to cicd VM
    environment: 
      name: deployment-vm
      resourceType: VirtualMachine
      tags: cicd  
    strategy:
      runOnce:
        deploy:
          steps:
          - script: git clone https://github.com/AlexTrinityBlock/blog.git
            displayName: '下載 Blog'