#baseURL = "https://alextrinityblock.github.io/blog/public/"
languageCode = "zh-hant"
title = "無面者小站"
theme = "ananke"

DefaultContentLanguage = "zh-tw"
SectionPagesMenu = "main" #上排標籤選單
Paginate = 3 # 單頁最大文章數量
# googleAnalytics = ""
# enableRobotsTXT = true

# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"

[params]
  favicon = "/blog/public/avatar2.jpg" #網站上頭的圖示
  site_logo = "/blog/public/logo.jpg" #網站左上角logo
  description = "歡迎來到無面者小站" #html meta 裡面的說明
#   facebook = ""
#   twitter = ""
#   instagram = ""
#   youtube = ""
#   github = ""
#   gitlab = ""
#   linkedin = ""
#   mastodon = ""
#   slack = ""
#   stackoverflow = ""
#   rss = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #無圖片時的背景顏色
  background_color_class = "mid-gray"

  # 下面的主頁面畫像在public/images裡頭
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/home.jpg"
  recent_posts_number = 3

