#上傳時記得啟動網址
baseURL = "https://alextrinityblock.github.io/blog/public/"
languageCode = "zh-hant"
title = "無面者小站"
theme = "ananke"
hasCJKLanguage = true

#分類選單單數與複數
pluralizelisttitles = false

DefaultContentLanguage = "zh-tw"
Paginate = 5 # 單頁最大文章數量
# googleAnalytics = ""
enableRobotsTXT = true

#上排選單設置
SectionPagesMenu = "main" #上排標籤選單

[[menu.main]]
    identifier = "linux"
    name = "linux"
    title = "linux"
    url = "/tags/linux"
    weight = 1
[[menu.main]]
    identifier = "hugo"
    name = "hugo"
    title = "hugo"
    url = "/tags/hugo"
    weight = 1
[[menu.main]]
    identifier = "c"
    name = "c"
    title = "c"
    url = "/tags/c/"
    weight = 1
[[menu.main]]
    identifier = "docker"
    name = "docker"
    title = "docker"
    url = "/tags/docker/"
    weight = 1
[[menu.main]]
    identifier = "network"
    name = "network"
    title = "network"
    url = "/tags/network/"
    weight = 1
[[menu.main]]
    identifier = "secure"
    name = "secure"
    title = "secure"
    url = "/tags/secure/"
    weight = 1
[[menu.main]]
    identifier = "python"
    name = "python"
    title = "python"
    url = "/tags/python/"
    weight = 1
[[menu.main]]
    identifier = "git"
    name = "git"
    title = "git"
    url = "/tags/git/"
    weight = 1
[[menu.main]]
    identifier = "math"
    name = "math"
    title = "math"
    url = "/tags/math/"
    weight = 1
[[menu.main]]
    identifier = "android"
    name = "android"
    title = "android"
    url = "/tags/android/"
    weight = 1
[[menu.main]]
    identifier = "html"
    name = "html"
    title = "html"
    url = "/tags/html/"
    weight = 1
[[menu.main]]
    identifier = "Node.js"
    name = "Node.js"
    title = "Node.js"
    url = "/tags/Node.js/"
    weight = 1
[[menu.main]]
    identifier = "ASP.net"
    name = "ASP.net"
    title = "ASP.net"
    url = "/tags/ASP.net/"
    weight = 1
[[menu.main]]
    identifier = "tags"
    name = "更多"
    title = "tags"
    url = "/tags/"
    weight = 2

[sitemap]
    changefreq = "monthly"
    priority = 2
    filename = "sitemap.xml"

[params]
  favicon = "/avatar2.jpg" #網站上頭的圖示
#  背景顏色
#  body_classes = "avenir bg-light-silver"
#  文章字體
#  post_content_classes = "avenir white"
  description = "歡迎來到無面者小站" #html meta 裡面的說明
#   site_logo = "/blog/public/logo2.jpg" #網站左上角logo
#   facebook = ""
#   twitter = ""
#   instagram = ""
#   youtube = ""
#   github = ""
#   gitlab = ""
#   linkedin = ""
#   mastodon = ""
#   slack = ""
#   stackoverflow = ""
#   rss = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #無圖片時的背景顏色
  background_color_class = "mid-gray"
  
  # 下面的主頁面畫像在public/images裡頭
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/home.jpg"
  recent_posts_number = 30

#允許html

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
